### ISSUE TITLE
Incosistency in API reference for Hedley

### ISSUE THREAD

**Issue by JuEeHa** [nemequ/nemequ.github.io#1]
HEDLEY_NON_NULL(...) has "... Variadic list of indexes (starting from 1, left-to-right) of parameters which must never be NULL. " in definition of parameters but example code has

```
HEDLEY_NON_NULL(0,2)
void do_something(Context* ctx_cant_be_null, Foo* maybe_null, Bar* cant_be_null);
```

**Comment by nemequ** [comment]
Oops.  Fixed (716f36baf76bf7eecb69ff9c9994e5fd0d285741), thanks.
